language: haskell

before_install:
  - cabal install hpc-coveralls
  - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - hlint . --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all
